name: Delete Terraform Plan Artifact
id: delete-terraform-artifact
description: Delete the terraform plan artifact

inputs:
  TF_STATE_SUBSCRIPTION_ID:
    description: Specifies the subscription id for the terraform state storage account.
    required: true
  TF_STATE_BLOB_ACCOUNT:
    description: Specifies the terraform storage account name
    required: true
  ARTIFACT_BLOB_CONTAINER:
    description: Specifies a container to upload the created artifact to
    default: 'tfartifact'

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ inputs.TF_STATE_SUBSCRIPTION_ID }}

    - name: Delete Terraform Artifact
      id: delete-artifact-action
      uses: azure/cli@v2
      with:
        inlineScript: |
          az storage blob delete \
            --auth-mode login \
            --account-name ${{ inputs.TF_STATE_BLOB_ACCOUNT }} \
            --container-name "${{ inputs.ARTIFACT_BLOB_CONTAINER }}" \
            --name "${{ github.run_id }}.zip" \
            --delete-snapshots include