name: Login to Azure Kubernetes
id: login-aks
description: Login to Azure Kubernetes

inputs:
  subscription_id:
    description: Specifies the subscription id for the AKS cluster
    required: true
  resource_group:
    description: Specifies the resource group for the AKS cluster
    required: true
  cluster_name:
    description: Specifies the Name for the AKS cluster
    required: true

runs:
  using: composite
  steps:
  - name: Install Kubelogin
    uses: azure/use-kubelogin@v1.2
    id: install-kubelogin-action
    with:
      kubelogin-version: 'v0.2.7'

  - name: Log in to Azure
    id: login-azure-action
    uses: azure/login@v2
    with:
      client-id: ${{ env.ARM_CLIENT_ID }}
      tenant-id: ${{ env.ARM_TENANT_ID }}
      subscription-id: ${{ inputs.subscription_id }}

  - name: Set Azure Kubernetes Context
    id: set-aks-context-action
    uses: azure/aks-set-context@v4
    with:
      resource-group: ${{ inputs.resource_group }}
      cluster-name: ${{ inputs.cluster_name }}

  - name: Set Kubeconfig TF_VAR
    id: set-kubeconfig-action
    shell: bash
    run: |
      kubelogin convert-kubeconfig -l azurecli
      echo "TF_VAR_kubeconfig=$KUBECONFIG"
      echo "TF_VAR_kubeconfig=$KUBECONFIG" >> $GITHUB_ENV