name: 'Setup Checkov'
description: 'Installs Checkov and sets up configuration file'

inputs:
  working_directory:
    description: 'Working directory for checkov configuration'
    required: true
  config_source_path:
    description: 'Path to the default checkov config to copy if none exists'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Checkov
      shell: bash
      run: |
        echo "Installing Checkov..."
        pip install checkov

    - name: Setup Checkov Config
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        CONFIG_FILE=".checkov.yml"
        if [ ! -f "$CONFIG_FILE" ]; then
          echo "Checkov config file ($CONFIG_FILE) not found in ${{ inputs.working_directory }}. Copying default config."
          cp "${{ inputs.config_source_path }}" .
          ls -la "$CONFIG_FILE"
        else
          echo "Using existing $CONFIG_FILE config file found in ${{ inputs.working_directory }}."
        fi