# filepath: /.github/actions/checkov-bicep/action.yml
name: 'Bicep Scan (Checkov)'
description: 'Builds Bicep to ARM JSON and scans with Checkov'

inputs:
  bicep_file_path:
    description: 'Path to the main Bicep file'
    required: true
  root_iac_folder_relative_path:
    description: 'Root path for Bicep files and output artifacts'
    required: true
  # compiled_arm_path: # Optional: Use if validate step already built the JSON
  #   description: 'Path to the pre-compiled ARM template JSON'
  #   required: false
  #   default: ''

runs:
  using: "composite"
  steps:
    - name: Install Checkov
      shell: bash
      run: |
        pip install --quiet checkov

    - name: Build Bicep to ARM JSON
      # Only run if compiled_arm_path is not provided
      # if: inputs.compiled_arm_path == ''
      shell: bash
      working-directory: ${{ inputs.root_iac_folder_relative_path }}
      run: |
        echo "Building Bicep to ARM JSON..."
        az bicep build --file ${{ inputs.bicep_file_path }} --outfile compiled.arm.json
        echo "COMPILED_ARM_JSON=${{ inputs.root_iac_folder_relative_path }}/compiled.arm.json" >> $GITHUB_ENV

    - name: Prepare Checkov Config
      shell: bash
      working-directory: ${{ inputs.root_iac_folder_relative_path }}
      run: |
        CONFIG_FILE=".checkov.yml"
        if [ ! -f "$CONFIG_FILE" ]; then
          echo "Checkov config file ($CONFIG_FILE) not found. Copying default config."
          cp "${{ github.action_path }}/.checkov.yml" .
          ls -la "$CONFIG_FILE"
        else
          echo "Using existing $CONFIG_FILE."
        fi

    - name: Run Checkov Scan
      id: checkov-scan-action
      uses: bridgecrewio/checkov-action@v12
      with:
        file: ${{ inputs.root_iac_folder_relative_path }}/compiled.arm.json
        repo_root_for_plan_enrichment: ${{ inputs.root_iac_folder_relative_path }}
        download_external_modules: true
        config_file: ${{ inputs.root_iac_folder_relative_path }}/.checkov.yml

    - name: Upload SARIF file
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: bicep-iac
        sarif_file: ${{ inputs.root_iac_folder_relative_path }}/results.sarif
