# filepath: /.github/actions/bicep-validate/action.yml
name: 'Bicep Deployment Stack Validate'
description: 'Runs az deployment stack validate'

inputs:
  deployment_scope:
    description: 'Scope: resourceGroup or subscription'
    required: true
  deployment_stack_name:
    description: 'Name for the Deployment Stack'
    required: true
  bicep_file_path:
    description: 'Path to the main Bicep file'
    required: true
  parameters_file_path:
    description: 'Path to the Bicep parameters file'
    required: true
  resource_group_name:
    description: 'Azure Resource Group name (if scope is resourceGroup)'
    required: false
    default: ''
  location:
    description: 'Azure region'
    required: true
  # outfile_path: # Optional output path for compiled ARM JSON
  #   description: 'Path to save the compiled ARM template JSON'
  #   required: false
  #   default: ''

# outputs: # Optional output
#   outfile_path:
#     description: 'Path to the compiled ARM template JSON'
#     value: ${{ inputs.outfile_path }}

runs:
  using: "composite"
  steps:
    - name: Run Validate
      shell: bash
      run: |
        echo "Running Bicep Validate..."
        cmd="az deployment stack ${{ inputs.deployment_scope }} validate"
        cmd+=" --name ${{ inputs.deployment_stack_name }}"
        cmd+=" --template-file ${{ inputs.bicep_file_path }}"
        cmd+=" --parameters ${{ inputs.parameters_file_path }}"
        cmd+=" --location ${{ inputs.location }}"
        if [[ "${{ inputs.deployment_scope }}" == "resourceGroup" ]]; then
          cmd+=" --resource-group ${{ inputs.resource_group_name }}"
        fi
        # if [[ -n "${{ inputs.outfile_path }}" ]]; then
        #   cmd+=" --outfile ${{ inputs.outfile_path }}"
        # fi
        echo "Executing: $cmd"
        $cmd
