# filepath: /.github/actions/bicep-what-if/action.yml
name: 'Bicep Deployment Stack What-If'
description: 'Runs az deployment stack what-if and optionally comments on PRs'

inputs:
  deployment_scope:
    description: 'Scope: resourceGroup, subscription, or managementGroup'
    required: true
  deployment_stack_name:
    description: 'Name for the Deployment Stack (used for naming the what-if operation)'
    required: true
  bicep_file_path:
    description: 'Path to the main Bicep file'
    required: true
  parameters_file_path:
    description: 'Path to the Bicep parameters file'
    required: true
  resource_group_name:
    description: 'Azure Resource Group name (required if scope is resourceGroup)'
    required: false
    default: ''
  management_group_id:
    description: 'Management Group ID (required if scope is managementGroup)'
    required: false
    default: ''
  location:
    description: 'Azure region'
    required: true
  github_token:
    description: 'GitHub token for PR comments'
    required: false
    default: ''

outputs:
  summary:
    description: 'Summary of the what-if operation'
    value: ${{ steps.run-whatif.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Run What-If
      id: run-whatif
      shell: bash
      run: |
        echo "Running Bicep What-If using Azure Deployment commands..."
        echo "Note: Using deployment what-if since stacks don't support what-if directly"
        
        # Determine the correct az deployment command based on scope
        case "${{ inputs.deployment_scope }}" in
          resourceGroup)
            if [[ -z "${{ inputs.resource_group_name }}" ]]; then
              echo "Error: resource_group_name is required for resourceGroup scope"
              exit 1
            fi
            cmd="az deployment group what-if"
            cmd+=" --resource-group ${{ inputs.resource_group_name }}"
            ;;
          subscription)
            cmd="az deployment sub what-if"
            cmd+=" --location ${{ inputs.location }}"
            ;;
          managementGroup)
            if [[ -z "${{ inputs.management_group_id }}" ]]; then
              echo "Error: management_group_id is required for managementGroup scope"
              exit 1
            fi
            cmd="az deployment mg what-if"
            cmd+=" --management-group-id ${{ inputs.management_group_id }}"
            cmd+=" --location ${{ inputs.location }}"
            ;;
          *)
            echo "Error: Unsupported deployment scope: ${{ inputs.deployment_scope }}"
            echo "Supported scopes: resourceGroup, subscription, managementGroup"
            exit 1
            ;;
        esac
        
        # Add common parameters
        cmd+=" --name ${{ inputs.deployment_stack_name }}-whatif"
        cmd+=" --template-file ${{ inputs.bicep_file_path }}"
        cmd+=" --parameters ${{ inputs.parameters_file_path }}"

        echo "Executing: $cmd"
        # Execute and capture output (handle potential errors)
        WHATIF_OUTPUT=$($cmd)
        echo "--- What-If Output ---"
        echo "$WHATIF_OUTPUT"
        echo "--- End What-If Output ---"

        # Simple summary for now - just use the raw output
        echo "summary<<EOF" >> $GITHUB_OUTPUT
        echo "$WHATIF_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post What-If Summary to PR
      if: inputs.github_token != '' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const whatIfOutput = `${{ steps.run-whatif.outputs.summary }}`;
          const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;

          if (!whatIfOutput || whatIfOutput.trim() === '') {
            console.log('What-if output is empty, skipping comment.');
            return;
          }

          // Use details tag for potentially long output
          const body = `## Bicep What-If Summary\n\n<details><summary>Click to expand What-If Output</summary>\n\n\`\`\`\n${whatIfOutput}\n\`\`\`\n\n</details>\n\n---\n*View full logs in the [GitHub Actions run](${runUrl}).*`;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: body.substring(0, 65535) // Ensure comment isn't too long
          });
          console.log('Posted Bicep what-if comment to PR #${context.issue.number}');
