name: Run Terraform Checkov Scan
id: run-terraform-checkov-scan
description: Runs a scan of terraform with Checkov

inputs:
  terraform_root_path:
    description: 'Relative path to root of Terraform code (usually ./iac)'
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Show Plan to Json
      id: tf-plan-json-action
      shell: bash
      working-directory: ${{ inputs.terraform_root_path }}
      run: |
        terraform show -json tfplan | jq '.' > tfplan.json

    - name: Terraform Scan with Checkov
      id: checkov-scan-action
      uses: bridgecrewio/checkov-action@v12
      with:
        file: ${{ inputs.terraform_root_path }}/tfplan.json
        repo_root_for_plan_enrichment: ${{ inputs.terraform_root_path }}
        download_external_modules: true
