name: Run Terraform Apply
id: run-terraform-apply
description: Runs the Terraform Apply

inputs:
  terraform_root_path:
    description: 'Relative path to root of Terraform code (usually ./iac)'
    required: true
  destroyResources:
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Apply
      id: tf-apply-action
      shell: bash
      working-directory: ${{ inputs.terraform_root_path }}
      run: |
        echo "Current working directory: $(pwd)"
        echo " "
        echo "Destroy flag set: ${{ inputs.destroyResources }}"
        echo " "

        terraform apply -input=false -auto-approve tfplan
