# filepath: /.github/workflows/bicep-apply-template.yml
name: Reusable Bicep Apply (Deploy)

on:
  workflow_call:
    inputs:
      deployment_scope:
        description: 'Scope of the deployment: resourceGroup or subscription'
        required: false
        type: string
        default: 'resourceGroup'
      deployment_stack_name:
        description: 'Name for the Azure Deployment Stack'
        required: true
        type: string
      bicep_file_path:
        description: 'Path to the main Bicep file (e.g., infra/main.bicep)'
        required: true
        type: string
      parameters_file_path:
        description: 'Path to the Bicep parameters file (e.g., infra/parameters/dev.parameters.json)'
        required: true
        type: string
      resource_group_name:
        description: 'Azure Resource Group name (required if scope is resourceGroup)'
        required: false
        type: string
        default: ''
      location:
        description: 'Azure region for deployment stack metadata and potentially resources'
        required: true
        type: string
      target_environment: # Optional: For linking to GitHub Environment
        description: 'Name of the GitHub Environment to associate the job with'
        required: false
        type: string
        default: ''
    secrets: # Allow passing Azure credentials
      ARM_CLIENT_ID:
        required: false
      ARM_CLIENT_SECRET:
        required: false
      ARM_TENANT_ID:
        required: false
      ARM_SUBSCRIPTION_ID:
        required: false

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  apply:
    name: "Bicep Apply (Deploy)"
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }} # Link to GitHub Environment if provided

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      # Optional: Could add a validation step here if desired before deploy

      - name: Bicep Deploy
        id: deployment
        uses: ./.github/actions/bicep-deploy
        with:
          deployment_scope: ${{ inputs.deployment_scope }}
          deployment_stack_name: ${{ inputs.deployment_stack_name }}
          bicep_file_path: ${{ inputs.bicep_file_path }}
          parameters_file_path: ${{ inputs.parameters_file_path }}
          resource_group_name: ${{ inputs.resource_group_name }}
          location: ${{ inputs.location }}

      - name: Print Deployment Outputs
        run: |
          echo "intOutput: ${{ steps.deployment.outputs }}"          