# filepath: /.github/workflows/bicep-plan-template.yml
name: Bicep Plan (What-If)

on:
  workflow_call:
    inputs:
      bicep_file_path:
        description: 'Path to the main Bicep file (e.g., infra/main.bicep)'
        required: true
        type: string
      parameters_file_path:
        description: 'Path to the Bicep parameters file (e.g., infra/parameters/dev.parameters.json)'
        required: true
        type: string
      deployment_scope:
        description: 'Scope of the deployment: resourceGroup or subscription'
        required: false
        type: string
        default: 'resourceGroup'
      deployment_name:
        description: 'Name for the Azure Deployment or Deployment Stack'
        default: ''
        type: string
      deployment_type:
        description: 'Type of deployment - deployment vs deploymentStack'
        required: false
        type: string
        default: 'deploymentStack'
      resource_group_name:
        description: 'Azure Resource Group name (required if scope is resourceGroup)'
        required: false
        type: string
        default: ''
      location:
        description: 'Azure region for deployment stack metadata and potentially resources'
        required: true
        type: string
      bypass_checks:
        description: 'Set to true to bypass linting and security scans'
        required: false
        type: boolean
        default: false
      github_token: # Only needed for PR commenting
        description: 'GitHub token for PR comments'
        required: false
        type: string
        default: ''
      target_environment: # Optional: For linking to GitHub Environment
        description: 'Name of the GitHub Environment to associate the job with'
        required: false
        type: string
        default: ''

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  # Define Bicep root relative to checkout path (adjust if needed)
  BICEP_ROOT_PATH: './iac' # Assuming Bicep files are relative to repo root

jobs:
  plan:
    name: "Bicep Plan (Validate & What-If)"
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }} # Link to GitHub Environment if provided

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Bicep Lint
        if: ${{ !inputs.bypass_checks }}
        uses: ./.github/actions/bicep-lint
        with:
          bicep_root_path: ${{ env.BICEP_ROOT_PATH }}
          bicep_file_path: ${{ inputs.bicep_file_path }}

      - name: Validate Deployment
        if: ${{ inputs.deployment_type == 'deployment' }}
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: ${{ inputs.deployment_name}}
          scope: ${{ inputs.deployment_scope }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ inputs.resource_group_name }}
          parameters-file: ${{ inputs.parameters_file_path }} #./main.bicepparam
          validation-level: providerNoRbac          

      - name: Validate Stack
        if: ${{ inputs.deployment_type == 'deploymentStack'}}
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: validate
          name: ${{ inputs.deployment_name}}
          location: ${{ inputs.location }}
          scope: ${{ inputs.deployment_scope }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          parameters-file: ${{ inputs.parameters_file_path }} #./main.bicepparam

      - name: What-If
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          name: ${{ inputs.deployment_name}}
          scope: ${{ inputs.deployment_scope }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ inputs.resource_group_name }}
          parameters-file: ${{ inputs.parameters_file_path }}
          validation-level: providerNoRbac                  

      - name: Bicep Scan (Checkov)
        if: ${{ !inputs.bypass_checks }}
        uses: ./.github/actions/checkov-bicep
        with:
          bicep_file_path: ${{ inputs.bicep_file_path }}
          bicep_root_path: ${{ env.BICEP_ROOT_PATH }}
