name: Bicep deploy template
on:
  workflow_call:
    inputs:
      bicep_action:
        description: 'Run Plan or Deploy'
        type: string
      runner_name:
        description: 'The name of the runner pool to run on'
        type: string
        default: 'ubuntu-latest'
      plan_target_environment:
        description: 'The environment to run the plan job against'
        type: string
      apply_target_environment:
        description: 'The environment to run the apply job against'
        type: string
      bicep_root_path:
        description: 'Relative path to root of Bicep code (usually ./iac)'
        default: './iac'
        type: string
      parameters_file_path:
        description: 'Path to bicep parameters file. Path is relative to the bicep root path.'
        type: string
      deployment_name:
        description: 'Name for the deployment'
        type: string
      deployment_scope:
        description: 'Scope of deployment: resourceGroup, subscription, or managementGroup'
        type: string
        default: 'resourceGroup'
      resource_group_name:
        description: 'Azure Resource Group name (required if scope is resourceGroup)'
        type: string
        default: ''
      management_group_id:
        description: 'Management Group ID (required if scope is managementGroup)'
        type: string
        default: ''
      location:
        description: 'Azure region for deployment'
        type: string
      bypass_checks:
        type: boolean
        default: false
      azure_subscription_id:
        description: 'Azure Subscription ID for this run (overrides env.ARM_SUBSCRIPTION_ID)'
        required: false
        type: string
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  bicep-plan:
    name: "Run bicep plan for ${{ inputs.plan_target_environment }}"
    uses: ./.github/workflows/bicep-plan-template.yml
    with:
      runner_name: ${{ inputs.runner_name }}
      target_environment: ${{ inputs.plan_target_environment }}
      bicep_root_path: ${{ inputs.bicep_root_path }}
      parameters_file_path: ${{ inputs.parameters_file_path }}
      deployment_name: ${{ inputs.deployment_name }}
      deployment_scope: ${{ inputs.deployment_scope }}
      resource_group_name: ${{ inputs.resource_group_name }}
      management_group_id: ${{ inputs.management_group_id }}
      location: ${{ inputs.location }}
      bypass_checks: ${{ inputs.bypass_checks }}
      azure_subscription_id: ${{ inputs.azure_subscription_id }}
      upload_artifact: ${{ inputs.bicep_action == 'deploy' }}
    secrets: inherit

  bicep-apply:
    needs: bicep-plan
    name: "Run bicep deploy for ${{ inputs.apply_target_environment }}"
    if: ${{ inputs.bicep_action == 'deploy' }}
    uses: ./.github/workflows/bicep-apply-template.yml
    with:
      runner_name: ${{ inputs.runner_name }}
      target_environment: ${{ inputs.apply_target_environment }}
      bicep_root_path: ${{ inputs.bicep_root_path }}
      parameters_file_path: ${{ inputs.parameters_file_path }}
      deployment_name: ${{ inputs.deployment_name }}
      deployment_scope: ${{ inputs.deployment_scope }}
      resource_group_name: ${{ inputs.resource_group_name }}
      management_group_id: ${{ inputs.management_group_id }}
      location: ${{ inputs.location }}
      azure_subscription_id: ${{ inputs.azure_subscription_id }}
    secrets: inherit