name: Terraform deploy template
on:
  workflow_call:
    inputs:
      terraform_action:
        description: 'Run Apply'
        type: string
      runner_name:
        description: 'The name of the runner pool to run on'
        type: string
        default: 'ubuntu-latest'
      environment_name_plan:
        description: 'The GitHub environment to run the plan job against'
        type: string
      environment_name_apply:
        description: 'The GitHub environment to run the apply job against'
        type: string
      root_module_folder_relative_path:
        description: 'Relative path to root of Terraform code (usually ./iac)'
        default: './iac'
        type: string
      tfvars_file:
        description: 'Comma seperated list of paths to optional tfvars files. Paths are relative to the terraform root path.'
        type: string
      tfstate_file:
        description: 'Backend Azure Storage Account Container file name (key) for Terraform state'
        type: string
      unlock_resource_firewalls:
        description: 'Unlock firewall for tf state storage and any extra unlocks'
        default: false
        type: boolean
      destroy_resources:
        type: boolean
        default: false
      bypass_static_analysis_checks:
        type: boolean
        default: false
      azure_subscription_id:
        description: 'Azure Subscription ID for this run (overrides env.ARM_SUBSCRIPTION_ID)'
        required: false
        type: string
        default: ''
      terraform_cli_version:
        description: 'Terraform CLI Version'
        default: 'latest'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: "Run terraform plan${{ inputs.destroy_resources && ' destroy' || '' }} for ${{ inputs.environment_name_plan }}"
    uses: ./.github/workflows/terraform-plan-template.yml
    with:
      runner_name: ${{ inputs.runner_name }}
      target_environment: ${{ inputs.environment_name_plan }}
      root_module_folder_relative_path: ${{ inputs.root_module_folder_relative_path }}
      tfvars_file: ${{ inputs.tfvars_file }}
      tfstate_file: ${{ inputs.tfstate_file }}
      unlock_resource_firewalls: ${{ inputs.unlock_resource_firewalls }}
      destroy_resources: ${{ inputs.destroy_resources }}
      bypass_static_analysis_checks: ${{ inputs.bypass_static_analysis_checks }}
      upload_artifact: ${{ contains(fromJSON('["destroy", "apply"]'), inputs.terraform_action) }}
      azure_subscription_id: ${{ inputs.azure_subscription_id }}
      terraform_version: ${{ inputs.terraform_cli_version }}
      secrets: inherit

  terraform-apply:
    needs: terraform-plan
    name: "Run terraform${{ inputs.destroy_resources && ' destroy' || ' apply' }} for ${{ inputs.environment_name_apply }}"
    if: ${{ contains(fromJSON('["destroy", "apply"]'), inputs.terraform_action) }}
    uses: ./.github/workflows/terraform-apply-template.yml
    with:
      runner_name: ${{ inputs.runner_name }}
      target_environment: ${{ inputs.environment_name_apply }}
      root_module_folder_relative_path: ${{ inputs.root_module_folder_relative_path }}
      tfstate_file: ${{ inputs.tfstate_file }}
      unlock_resource_firewalls: ${{ inputs.unlock_resource_firewalls }}
      destroy_resources: ${{ inputs.destroy_resources }}
      azure_subscription_id: ${{ inputs.azure_subscription_id }}
      terraform_version: ${{ inputs.terraform_cli_version }}      